# -*- coding: utf-8 -*-
"""Lab 6_ MARTINEZ_SOTO_ROBERTO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UWieHVWZ-NM8hinLuctbv3iblRpMsvdY

# Lab 6. Introduction to Dictionaries in Python

## Learning Objectives
By the end of this lab, students will be able to:
Define and explain the purpose of a dictionary in Python.
Create and manipulate dictionaries.
Access, modify, add, and remove dictionary elements.
Iterate through dictionary contents.
Compare dictionaries with lists and identify appropriate use cases.
Apply dictionaries to solve simple real-world problems.

## 1. Core Concepts
What is a Dictionary?

A dictionary is a data structure that stores information as key-value pairs.

### General structure:
- key -> value
#### Example:
- "name" -> "Alice"
- "age" -> 20
- "major" -> "Computer Science"

Unlike lists, which store elements using numerical positions (indexes), dictionaries store and retrieve information using unique keys.

### Why Do We Need Dictionaries?
Consider the following example using lists:
"""

students = ["Alice", "Bob", "Charlie"]
grades = [95, 80, 100]

"""To find Charlie's grade:


"""

index = students.index("Charlie")
print(grades[index])

"""

This approach becomes inefficient and difficult to maintain as the amount of data grows.

Using a dictionary:
"""

grades = {
    "Alice": 95,
    "Bob": 80,
    "Charlie": 100
}

print(grades["Charlie"])

"""The dictionary directly associates each student with a grade.



## Key Concepts

A dictionary consists of:

### Key

The identifier used to access information.

```python
"name"
```

### Value

The data associated with a key.

```python
"Alice"
```

### Key-Value Pair

```python
"name": "Alice"
```

### Dictionary:

```python
student = {
    "name": "Alice",
    "age": 20,
    "major": "Computer Science"
}
```


# Dictionary vs List

| List                 | Dictionary               |
| -------------------- | ------------------------ |
| Uses indexes         | Uses keys                |
| Ordered sequence     | Key-value mapping        |
| Access by position   | Access by identifier     |
| Example: students[0] | Example: student["name"] |

Understanding this distinction is the most important learning outcome of this lab.


# 2. Creating a Dictionary

### Reflection Question

What is the key associated with the value `"Alice"`?

**Answer:** name


# 3. Accessing Values

Values are accessed using their corresponding keys.

Expected output:

```text
Alice
```



##Exercise 1

Print the student's age.

"""

student = {
    "name": "Alice",
    "age": 20,
    "major": "Computer Science"
}

student = {
    "name": "Alice",
    "age": 20,
    "major": "Computer Science"
}
print(student["age"])

"""



# 4. Modifying Existing Values

A value can be updated by assigning a new value to an existing key.


## Exercise 2

Change the Alice's major to:

```text
Information Technology
```
"""

student = {
    "name": "Alice",
    "age": 20,
    "major": "Computer Science"
}

student = {
    "name": "Alice",
    "age": 20,
    "major": "Computer Science"
}

student["major"]="Information Technology"
print(student["major"])

"""


# 5. Adding New Key-Value Pairs

New information can be added dynamically.


## Exercise 3

Add a new key called:

```text
semester
```

with the value:

```text
3
```
"""

student = {
    "name": "Alice",
    "age": 20
}

student = {
    "name": "Alice",
    "age": 20
}
student["semester"]=3
print(student["semester"])

"""



# 6. Iterating Through a Dictionary

Dictionaries can be traversed using a loop.

Expected output:

```text
name : Alice
age : 20
major : Computer Science
```


## Exercise 4

Print all information stored in the following dictionary.

"""

game_character = {
    "name": "Mario",
    "lives": 3,
    "level": 5,
    "coins": 120
}

game_character = {
    "name": "Mario",
    "lives": 3,
    "level": 5,
    "coins": 120
}
for key in game_character:
  value=game_character[key]
  print(f"{key} : {value}")

"""# 7. Practical Application: Student Grade Registry
- Problem Statement
- Create a program that:
- Creates an empty dictionary.
- Requests information for three students.
- Stores each student's name and grade.
- Displays the completed dictionary.
## Example Input




```
Name: Alice
Grade: 95

Name: Bob
Grade: 80

Name: Charlie
Grade: 100
```

Expected Output:
"""

{
    'Alice': 95,
    'Bob': 80,
    'Charlie': 100
}

"""## Exercise 5
Complete the program below.
"""

grades = {}
for i in range (0,3):
  student=(input("Put the name of the student "))
  grade=float(input("Put the grade of the student "))
  grades[student]=grade
for key in grades:
  value=grades[key]
  print(f"{key}: {value}")
# Write your solution here

"""## 8. Retrieving Information
Using the dictionary created in the previous exercise, ask the user for a student's name and display the corresponding grade.
### Example


```
Student: Charlie

Grade: 100
```

## Exercise 6


"""

grades = {}
for i in range (0,3):
  student=(input("Put the name of the student "))
  grade=float(input("Put the grade of the student "))
  grades[student]=grade
for key in grades:
  value=grades[key]
  print(f"{key}: {value}")
search_student=input("Search student: ")
student_grade=grades[search_student]
print(f"Grade is: {student_grade} ")

"""## 9. Challenge Activity
####Character Statistics Manager

Create a dictionary containing:


```
name
health
attack
defense
level
```

The program must:
1. Display all character information.
2. Increase the level by 1.
3. Increase the attack value by 10.
4. Display the updated information.

## Workspace
"""

statistics={
    "name":"Carlos",
    "health":100,
    "attack":30,
    "defense":20,
    "level":5,
}
for key in statistics:
  value=statistics[key]
  print(f"{key}: {value}")
print("level up! ")
statistics["level"]=statistics["level"]+1
statistics["attack"]=statistics["attack"]+10
for key in statistics:
  value=statistics[key]
  print(f"{key}: {value}")

"""## Critical Thinking Questions
1. What is the main difference between a list and a dictionary?

Answer: A list is focused on the position of the data, the dictionary saves values in "keys" that is like an agenda.

2. Why are dictionaries more suitable than lists for storing student grades associated with names?

Answer: Because you dont longer have to focuse on the position of the student. This is useful for managing the storage, adding or modifing values inside.

3. Give one real-world example where a dictionary would be more useful than a list.

Answer: On situations where your need to search something without checking the list. An example could be a data base of an ecommerce, where they need to find items with its SKU.

4. What would happen if two different values were assigned to the same key?

Answer: It depends of the order. The last value that is assigned will overwrite the other.

5. In your own words, explain the concept of a key-value pair.

Answer: Its how the dictionary works. The key is the identifier and the value is what is storage on it.

## Submission Requirements

Students must submit:

1. A fully executed Google Colab notebook.
2. All exercises completed.
3. All critical thinking questions answered.
4. Outputs visible for every exercise.
5. Clear and properly documented code.
6. A copy of the completed and executed notebook uploaded to their course repository in the following location:

```text
Unit 2/
```

7. Verify that the notebook has been successfully pushed to the repository before submission.
8. Mark the corresponding assignment in Google Classroom as **Done/Turned In** after completing all requirements above.

### Submission Checklist

Before marking the assignment as complete, verify that:

* [ ] The notebook runs from start to finish without errors.
* [ ] All exercises are completed.
* [ ] All reflection questions are answered.
* [ ] Outputs are visible for every section.
* [ ] The notebook is properly documented and readable.
* [ ] A copy of the notebook has been uploaded to the repository under the **Unit 2** folder.
* [ ] Changes have been committed and pushed successfully.
* [ ] The assignment has been marked as **Done/Turned In** in Google Classroom.

Failure to complete both the repository submission and the Google Classroom submission may result in the assignment being considered incomplete.

# Summary
*A dictionary is a collection of key-value pairs that allows information to be stored and retrieved using meaningful identifiers rather than numerical positions. Dictionaries are one of the most important data structures and are widely used in data processing, APIs, configuration files, databases, machine learning, and software development. Understanding dictionaries is essential for working with structured data efficiently.*

# References

- Matthes, E. (2023). Python crash course: A hands-on, project-based introduction to programming (3rd ed.). No Starch Press.
- Downey, A. B. (2024). Think Python: How to think like a computer scientist (3rd ed.). O'Reilly Media.
- Guttag, J. V. (2021). Introduction to computation and programming using Python (3rd ed.). MIT Press.
- Ramalho, L. (2022). Fluent Python: Clear, concise, and effective programming (2nd ed.). O'Reilly Media.
"""