# -*- coding: utf-8 -*-
"""Lab5. Programming Paradigms Comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RDLxlNSCGYjOqkfJ2D4pSNVNSG2MV57v

# Lab5. Programming Paradigms Comparison

**Student Name:** Martinez Soto Roberto  
**Group:** 3A BIS  
**Date:** 20/05/2026  

---

# Objective

You will solve the same problem using different programming paradigms.

The goal is to understand how the way you think and structure a solution changes depending on the paradigm.



# Required Paradigms

You must implement the solution using ALL of the following paradigms:

1. Imperative Programming  
2. Structured Programming (functions + control structures)  
3. Modular Programming  
4. Object-Oriented Programming (OOP)  
5. Functional Programming (basic level)


# Important Rules

- The SAME problem must be used in all paradigms.
- You must NOT copy-paste the same solution with small changes.
- Each paradigm must show a different way of structuring the solution.
- Each section must include:
  - explanation in your own words
  - working code
  - a personal modification
  - a short reflection[texto del vínculo](https://)


# Problem Description

Describe the problem you will solve:

```text
A system that calculates the average grade of students and determines if they pass or fail.

# 1. 1. Imperative Programming  

## Brief Explanation
Imperative programming is a paradigm that indicates the computer how to solve a solution. It focuses on how to solve a problem rather than just the result.

## Code Example
"""

#Python code here
# Given data
grades = [70, 80, 90]
total=0
for i in grades:
  total += 1
  average = total/len(grades)
  print(average)
# 1. Calculate sum using a loop
# 2. Compute average
# 3. Print result

"""## Your Modification
What did you change and why?

Example: I added a function to calculate the highest grade and printed it together with the average.


## Reflection
What did you learn from this approach and how does it compare to others?

# 1. 2. Structured Programming  

## Brief Explanation
Imperative programming is a paradigm that organize everything into clear blocks.

## Code Example
"""

# Given data
order = [{"price": 100, "valid": True}, {"price": 50, "valid": False}, {"price": 200, "valid": True}]
tax_rate = 0.16

def analyze_and_calculate_order(cart, tax):
    # 1. Calculate sum using a loop (only valid items)
    subtotal = 0
    valid_count = 0

    for item in cart:
        if item["valid"]:
            subtotal += item["price"]
            valid_count += 1

    # 2. Compute average (avoiding division by zero if cart is empty)
    average_price = subtotal / valid_count if valid_count > 0 else 0

    # Final total calculation
    total_with_tax = subtotal * (1 + tax)

    # 3. Print result
    print(f"--- Order Summary ---")
    print(f"Subtotal (Valid Items): ${subtotal:.2f}")
    print(f"Average Price of Valid Items: ${average_price:.2f}")
    print(f"Total Structured (with Tax): ${total_with_tax:.2f}")

    return total_with_tax

# Execution
final_total = analyze_and_calculate_order(order, tax_rate)

"""## Your Modification
What did you change and why? *Added an absolute maximum budget cap parameter to the function. If the subtotal exceeds the cap, it restricts the execution and raises an message or clips the total.*

## Reflection
What did you learn from this approach and how does it compare to others? *Enclosing the logic into a function makes it clear what the inputs and outputs are. It stops variables from bleeding into other parts of the script.*

# 1. 3. Modular Programming  

## Brief Explanation
Breaks the program into distinct, independent sub-modules or functions where each handles one specific job. Instead of one big calculation function, tasks are decoupled into filters, math logic, and formatting handlers.

## Code Example
"""

# Given data
order = [{"price": 100, "valid": True}, {"price": 50, "valid": False}, {"price": 200, "valid": True}]
tax_rate = 0.16

# --- Módulos / Funciones de una sola responsabilidad ---

def get_valid_items(cart):
    """Filtra el carrito para dejar solo los elementos válidos."""
    return [item for item in cart if item["valid"]]

def calculate_sum(items):
    """1. Calculate sum using a loop"""
    total_sum = 0
    for item in items:
        total_sum += item["price"]
    return total_sum

def compute_average(total_sum, count):
    """2. Compute average"""
    if count == 0:
        return 0
    return total_sum / count

def apply_tax(amount, tax):
    """Calcula el monto final con impuestos."""
    return amount * (1 + tax)

def print_summary(subtotal, average, total):
    """3. Print result"""
    print(f"--- Modular Order Summary ---")
    print(f"Subtotal: ${subtotal:.2f}")
    print(f"Average Price: ${average:.2f}")
    print(f"Total with Tax: ${total:.2f}")

# --- Orquestación del Pipeline ---
def process_order_pipeline(cart, tax):
    # Filtrado inicial
    valid_items = get_valid_items(cart)

    # Ejecución de los pasos modulares
    subtotal = calculate_sum(valid_items)
    average = compute_average(subtotal, len(valid_items))
    final_total = apply_tax(subtotal, tax)

    # Salida
    print_summary(subtotal, average, final_total)
    return final_total

# Execution
process_order_pipeline(order, tax_rate)

"""## Your Modification
What did you change and why? *Intercepted the pipeline by adding a completely separate, independent module function (apply_shipping) that injects a flat shipping fee if the subtotal falls below a specific threshold.*

## Reflection
What did you learn from this approach and how does it compare to others? *This is incredibly flexible. Because each block does exactly one thing, I could add the shipping logic into the middle of the computation without breaking or modifying the code inside the other existing functions.*
"""



"""# 1. 4. Object Oriented Programming  

## Brief Explanation
Models the solution around "objects" containing both data (attributes) and behavior (methods). It groups state and logic together inside classes to mimic real-world entities.

## Code Example

"""

# Modified Solution
class CartItem:
    def __init__(self, price, valid):
        self.price = price
        self.valid = valid

class InvoiceCalculator:
    def __init__(self, tax_rate):
        self.tax_rate = tax_rate

    def calculate(self, items):
        subtotal = sum(item.price for item in items if item.valid)
        return subtotal * (1 + self.tax_rate)

# Extended behavior via inheritance
class LoyaltyInvoiceCalculator(InvoiceCalculator):
    def __init__(self, tax_rate, loyalty_discount):
        super().__init__(tax_rate)
        self.loyalty_discount = loyalty_discount  # e.g., 0.05 for 5%

    def calculate(self, items):
        subtotal = sum(item.price for item in items if item.valid)
        discounted_subtotal = subtotal * (1 - self.loyalty_discount)
        return discounted_subtotal * (1 + self.tax_rate)

items_obj = [CartItem(100, True), CartItem(50, False), CartItem(200, True)]
vip_calculator = LoyaltyInvoiceCalculator(0.16, 0.05)
print(f"Modified Total OOP (VIP): ${vip_calculator.calculate(items_obj)}")

"""## Your Modification
What did you change and why? *Used inheritance to expand the behavior. Created a specialized child class LoyaltyInvoiceCalculator that overrides the calculation behavior to apply a point-based or percentage discount based on user status.*

## Reflection
What did you learn from this approach and how does it compare to others? *OOP makes managing state highly intuitive. By keeping attributes inside instances, extending functionality via inheritance doesn't require modifying the original parent class structure at all.*
"""



"""# 1. 5. Functional Programming  

## Brief Explanation
Treats computation as the evaluation of mathematical functions, avoiding changing states and mutable data. It utilizes higher-order functions like filter() and map(), or pure list comprehensions to declare what the result should be without loops.

## Code Example

"""

# Modified Solution
order = [
    {"price": 100, "valid": True, "premium": False},
    {"price": 50, "valid": False, "premium": False},
    {"price": 200, "valid": True, "premium": True}
]
tax_rate = 0.16

# Modifying logic completely inline via lambda transformations
valid_items = filter(lambda x: x["valid"], order)
adjusted_prices = map(lambda x: x["price"] * 2 if x["premium"] else x["price"], valid_items)
modified_total = sum(adjusted_prices) * (1 + tax_rate)

print(f"Modified Total Functional: ${modified_total}")

"""## Your Modification
What did you change and why? *Injected a conditional calculation step natively inside the functional flow using a ternary expression inside a map operation to double the price of items flagged as "premium" items before summing.*

## Reflection
What did you learn from this approach and how does it compare to others? *Functional code is highly concise and eliminates bugs related to tracking state transformations over time. It can be harder to parse mentally if lambdas get overly dense, but it ensures data immutability.*
"""

